# Generated by Django 5.0.6 on 2024-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_paper_content_alter_paper_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="content",
            field=models.FileField(null=True, upload_to="papers"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
