# Generated by Django 5.0.6 on 2024-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_paper_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="slug",
            field=models.SlugField(default="", max_length=200),
        ),
    ]
