# Generated by Django 5.0.6 on 2024-07-20 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_paper_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
