# Generated by Django 5.0.6 on 2024-07-24 21:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_paper_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="description",
            field=tinymce.models.HTMLField(max_length=400, null=True),
        ),
    ]
