# Generated by Django 5.0.6 on 2024-07-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_paper_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="description",
            field=models.TextField(max_length=400, null=True),
        ),
    ]
